# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import em_pb2 as em__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in em_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExclusionManagerStub(object):
    """Service definition for mutual exclusion coordination
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestEntry = channel.unary_unary(
                '/exclusion_manager.ExclusionManager/RequestEntry',
                request_serializer=em__pb2.RequestMessage.SerializeToString,
                response_deserializer=em__pb2.ReplyMessage.FromString,
                _registered_method=True)
        self.ReplyEntry = channel.unary_unary(
                '/exclusion_manager.ExclusionManager/ReplyEntry',
                request_serializer=em__pb2.RequestMessage.SerializeToString,
                response_deserializer=em__pb2.ReplyMessage.FromString,
                _registered_method=True)
        self.ReleaseEntry = channel.unary_unary(
                '/exclusion_manager.ExclusionManager/ReleaseEntry',
                request_serializer=em__pb2.ReleaseMessage.SerializeToString,
                response_deserializer=em__pb2.ReplyMessage.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/exclusion_manager.ExclusionManager/GetStatus',
                request_serializer=em__pb2.StatusRequest.SerializeToString,
                response_deserializer=em__pb2.StatusResponse.FromString,
                _registered_method=True)


class ExclusionManagerServicer(object):
    """Service definition for mutual exclusion coordination
    """

    def RequestEntry(self, request, context):
        """Request entry to critical section
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplyEntry(self, request, context):
        """Reply to a request (used in some algorithms)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseEntry(self, request, context):
        """Release critical section
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Optional: Health check or status query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExclusionManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestEntry,
                    request_deserializer=em__pb2.RequestMessage.FromString,
                    response_serializer=em__pb2.ReplyMessage.SerializeToString,
            ),
            'ReplyEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplyEntry,
                    request_deserializer=em__pb2.RequestMessage.FromString,
                    response_serializer=em__pb2.ReplyMessage.SerializeToString,
            ),
            'ReleaseEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseEntry,
                    request_deserializer=em__pb2.ReleaseMessage.FromString,
                    response_serializer=em__pb2.ReplyMessage.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=em__pb2.StatusRequest.FromString,
                    response_serializer=em__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'exclusion_manager.ExclusionManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('exclusion_manager.ExclusionManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExclusionManager(object):
    """Service definition for mutual exclusion coordination
    """

    @staticmethod
    def RequestEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exclusion_manager.ExclusionManager/RequestEntry',
            em__pb2.RequestMessage.SerializeToString,
            em__pb2.ReplyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplyEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exclusion_manager.ExclusionManager/ReplyEntry',
            em__pb2.RequestMessage.SerializeToString,
            em__pb2.ReplyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exclusion_manager.ExclusionManager/ReleaseEntry',
            em__pb2.ReleaseMessage.SerializeToString,
            em__pb2.ReplyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exclusion_manager.ExclusionManager/GetStatus',
            em__pb2.StatusRequest.SerializeToString,
            em__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
